variables:
  DOCKER_TAG: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE: sogno/pintura

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - test
  - build
  - deploy

build:docker:
  stage: build
  script:
    - docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
  tags:
    - shell

deploy:docker:
  stage: deploy
  script:
    - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
    - eval $(ssh-agent -s)
    - echo "${SSH_DEPLOY_KEY}" | perl -p -e 's/&&&&&&&&/\n/g' | ssh-add - > /dev/null
    - ssh -l ubuntu -o "StrictHostKeyChecking=no"  "${VM_IP}" "cd pintura &&
           git checkout master &&
           git pull &&
           ./stop_docker.sh &&
           docker system prune -f &&
           make docker &&
           make start"
  dependencies:
    - build:docker
  tags:
    - shell
  only:
    refs:
      - master
